-- Adicionar categorias
INSERT INTO category (id, name, description, icon_name) VALUES ('58d23991-7f10-4af3-8fcb-52a9a24697de', 'domésticos', 'Serviços relacionados a cuidados e manutenções em casa, como limpeza e organização.', 'LampFloor');
INSERT INTO category (id, name, description, icon_name) VALUES ('1246f8d1-5bdf-4b9c-b7e4-49e3afc55ba8', 'elétrico', 'Serviços de instalação e manutenção elétrica para residências e empresas.', 'Bolt');
INSERT INTO category (id, name, description, icon_name) VALUES ('dbd56a8d-8731-4094-9be3-5e824e9f7387', 'manutenção', 'Serviços gerais de reparo e manutenção em diversos tipos de imóveis.', 'Wrench');
INSERT INTO category (id, name, description, icon_name) VALUES ('7b8dcde3-50a1-4098-9382-03b61f5479cd', 'administração', 'Serviços administrativos, como gestão de projetos e suporte ao cliente.', 'Briefcase');
INSERT INTO category (id, name, description, icon_name) VALUES ('47cb792b-75cf-470a-94fa-76be1a0298c4', 'consultoria', 'Consultoria em diversas áreas para ajudar a melhorar processos e estratégias.', 'User');
INSERT INTO category (id, name, description, icon_name) VALUES ('50ba3bb8-3b23-4d49-8f29-17af99c7403d', 'contabilidade', 'Serviços contábeis para gestão financeira, planejamento fiscal e mais.', 'Calculator');
INSERT INTO category (id, name, description, icon_name) VALUES ('cf6bc7cf-1c3a-4f85-ae80-6b90c20f7e95', 'design', 'Serviços de design gráfico, web design, criação de logotipos e muito mais.', 'Brush');
INSERT INTO category (id, name, description, icon_name) VALUES ('85c12d9e-0af9-4ad8-83a5-04677af15bde', 'engenharia', 'Serviços de engenharia civil, mecânica, elétrica e outros ramos da engenharia.', 'HardHat');
INSERT INTO category (id, name, description, icon_name) VALUES ('7d485a16-1ee9-4ff6-8fd4-cba3c9fe4a1d', 'Data Entry', 'Serviços de entrada de dados e organização de informações.', 'Scroll');
INSERT INTO category (id, name, description, icon_name) VALUES ('f1c9378e-b33c-4fd4-86bc-8bb8db82c318', 'Social Media Management', 'Gerenciamento de redes sociais e criação de conteúdo.', 'Megaphone');
INSERT INTO category (id, name, description, icon_name) VALUES ('e8b123a3-4a29-4d47-bb1f-01c43e78f0d5', 'jurídico', 'Serviços legais, como consultoria jurídica e representação em processos.', 'Gavel');
INSERT INTO category (id, name, description, icon_name) VALUES ('f3dcb593-5f36-4b4c-910f-ada5018c3e98', 'marketing', 'Serviços de marketing digital, criação de campanhas publicitárias e branding.', 'Megaphone');
INSERT INTO category (id, name, description, icon_name) VALUES ('4d5304c8-6f24-4d07-b844-6f6b6cf5f6c5', 'saúde', 'Serviços de cuidados com a saúde, como atendimento médico, fisioterapia e mais.', 'Heart');
INSERT INTO category (id, name, description, icon_name) VALUES ('de0f1b7c-5317-4b1f-8b1f-4cb23980d7c0', 'tecnologia', 'Serviços de TI, desenvolvimento de software, suporte técnico e mais.', 'Monitor');
INSERT INTO category (id, name, description, icon_name) VALUES ('e60b9c6e-77cc-4b53-9316-b003f005a69e', 'transporte', 'Serviços de transporte e logística, incluindo entregas e mudanças.', 'Truck');
INSERT INTO category (id, name, description, icon_name) VALUES ('dbfdf6fa-34d5-49f8-9f6c-4b31a5dc57ef', 'vendas', 'Serviços relacionados a vendas, desde vendedores a representantes comerciais.', 'BadgeDollarSign');
INSERT INTO category (id, name, description, icon_name) VALUES ('a49e4f41-4f7f-49cb-b38c-47620894b509', 'fotografia', 'Serviços de fotografia para eventos, retratos, produtos e mais.', 'Camera');
INSERT INTO category (id, name, description, icon_name) VALUES ('f79e44d4-2f53-4cb5-9332-62902af2d9e8', 'música', 'Serviços musicais, como aulas de instrumentos, produção musical e mais.', 'Music');
INSERT INTO category (id, name, description, icon_name) VALUES ('6a6d98c3-45c1-4f64-9e3f-3e6d43c3f6c6', 'educação', 'Serviços educacionais, como tutoria, ensino e formação acadêmica.', 'BookOpen');
INSERT INTO category (id, name, description, icon_name) VALUES ('bf34c6b0-5dcb-4c2d-8d2c-e90950e6e91f', 'idiomas', 'Serviços de ensino de idiomas, tradução e interpretação.', 'Languages');
INSERT INTO category (id, name, description, icon_name) VALUES ('67c48c73-c8d5-4c8e-b60e-1f79e2ac7ae6', 'esportes', 'Serviços relacionados a esportes, como treinamentos, personal trainers e mais.', 'Dumbbell');
INSERT INTO category (id, name, description, icon_name) VALUES ('2d7e5ff8-85b0-4b79-b1f8-150f54550ee8', 'culinária', 'Serviços culinários, como chefs particulares, aulas de culinária e mais.', 'Utensils');
INSERT INTO category (id, name, description, icon_name) VALUES ('b14cdca0-48d4-4264-b13c-b658c92f9d0b', 'beleza', 'Serviços de beleza, como cabeleireiros, maquiadores e estética em geral.', 'Scissors');
INSERT INTO category (id, name, description, icon_name) VALUES ('3ebc5b32-73e8-4d7e-b44d-19d5730a9642', 'moda', 'Serviços de moda, como consultoria de estilo, design de roupas e mais.', 'Shirt');
INSERT INTO category (id, name, description, icon_name) VALUES ('5ab1ef10-65c0-4b98-b2b3-e305c8de9e43', 'artesanato', 'Serviços de artesanato, incluindo criação de itens personalizados e decoração.', 'Scroll');
